"""
GitHub Portfolio Generator
Automatically creates and deploys a portfolio page to GitHub Pages
"""

import os
import json
import base64
import requests
from typing import Dict, Optional
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class GitHubPortfolioGenerator:
    """Generate and deploy portfolio to GitHub Pages"""
    
    def __init__(self, github_token: str):
        """
        Initialize GitHub Portfolio Generator
        
        Args:
            github_token: GitHub Personal Access Token with repo permissions
        """
        self.github_token = github_token
        self.base_url = "https://api.github.com"
        self.headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    def verify_token(self) -> Dict:
        """
        Verify GitHub token is valid
        
        Returns:
            dict with success status and user info
        """
        try:
            response = requests.get(
                f"{self.base_url}/user",
                headers=self.headers
            )
            
            if response.status_code == 200:
                user_data = response.json()
                return {
                    "success": True,
                    "username": user_data.get("login"),
                    "name": user_data.get("name"),
                    "email": user_data.get("email")
                }
            else:
                return {
                    "success": False,
                    "error": "Invalid GitHub token"
                }
        except Exception as e:
            logger.error(f"Error verifying token: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def create_repository(self, username: str, repo_name: str = None) -> Dict:
        """
        Create GitHub repository for portfolio
        
        Args:
            username: GitHub username
            repo_name: Repository name (defaults to username.github.io)
            
        Returns:
            dict with success status and repo info
        """
        if repo_name is None:
            repo_name = f"{username}.github.io"
        
        try:
            # Check if repo already exists
            check_response = requests.get(
                f"{self.base_url}/repos/{username}/{repo_name}",
                headers=self.headers
            )
            
            if check_response.status_code == 200:
                logger.info(f"Repository {repo_name} already exists")
                return {
                    "success": True,
                    "repo_name": repo_name,
                    "exists": True,
                    "message": "Repository already exists"
                }
            
            # Create new repository
            create_data = {
                "name": repo_name,
                "description": "My Professional Portfolio - Generated by Viqri CV",
                "homepage": f"https://{username}.github.io",
                "private": False,
                "auto_init": True
            }
            
            response = requests.post(
                f"{self.base_url}/user/repos",
                headers=self.headers,
                json=create_data
            )
            
            if response.status_code == 201:
                return {
                    "success": True,
                    "repo_name": repo_name,
                    "exists": False,
                    "message": "Repository created successfully"
                }
            else:
                return {
                    "success": False,
                    "error": f"Failed to create repository: {response.json().get('message', 'Unknown error')}"
                }
                
        except Exception as e:
            logger.error(f"Error creating repository: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def generate_portfolio_html(self, cv_data: Dict) -> str:
        """
        Generate portfolio HTML from CV data
        
        Args:
            cv_data: Extracted CV information
            
        Returns:
            HTML string for portfolio page
        """
        personal = cv_data.get("personal_info", {})
        summary = cv_data.get("professional_summary", "")
        experience = cv_data.get("experience", [])
        education = cv_data.get("education", [])
        skills = cv_data.get("skills", {})
        projects = cv_data.get("projects", [])
        certifications = cv_data.get("certifications", [])
        awards = cv_data.get("awards", [])
        
        # Get all skills as a flat list
        all_skills = []
        for skill_category in skills.values():
            if isinstance(skill_category, list):
                all_skills.extend(skill_category)
        
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{personal.get('name', 'Professional Portfolio')} - {summary[:150] if summary else 'Professional Portfolio'}">
    <meta name="author" content="{personal.get('name', '')}">
    <title>{personal.get('name', 'My Portfolio')} | Professional Portfolio</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
    
    <style>
        :root {{
            --primary-color: #2563eb;
            --secondary-color: #1e40af;
            --accent-color: #8b5cf6;
            --text-primary: #1f2937;
            --text-secondary: #6b7280;
            --bg-primary: #ffffff;
            --bg-secondary: #f9fafb;
            --border-color: #e5e7eb;
            --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.05);
            --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.07);
            --shadow-lg: 0 10px 15px rgba(0, 0, 0, 0.1);
        }}
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Inter', sans-serif;
            color: var(--text-primary);
            line-height: 1.6;
            background: var(--bg-secondary);
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
        }}
        
        /* Header */
        header {{
            background: linear-gradient(135deg, var(--primary-color), var(--accent-color));
            color: white;
            padding: 4rem 0;
            text-align: center;
            position: relative;
            overflow: hidden;
        }}
        
        header::before {{
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="rgba(255,255,255,0.1)" d="M0,96L48,112C96,128,192,160,288,160C384,160,480,128,576,112C672,96,768,96,864,112C960,128,1056,160,1152,165.3C1248,171,1344,149,1392,138.7L1440,128L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>') no-repeat bottom;
            background-size: cover;
            opacity: 0.3;
        }}
        
        header .container {{
            position: relative;
            z-index: 1;
        }}
        
        h1 {{
            font-family: 'Playfair Display', serif;
            font-size: 3rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
        }}
        
        .tagline {{
            font-size: 1.25rem;
            font-weight: 300;
            margin-bottom: 2rem;
            opacity: 0.95;
        }}
        
        .contact-links {{
            display: flex;
            gap: 1.5rem;
            justify-content: center;
            flex-wrap: wrap;
            margin-top: 2rem;
        }}
        
        .contact-link {{
            color: white;
            text-decoration: none;
            padding: 0.75rem 1.5rem;
            background: rgba(255, 255, 255, 0.2);
            border-radius: 50px;
            backdrop-filter: blur(10px);
            transition: all 0.3s ease;
            display: flex;
            align-items: center;
            gap: 0.5rem;
            font-weight: 500;
        }}
        
        .contact-link:hover {{
            background: rgba(255, 255, 255, 0.3);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        }}
        
        /* Sections */
        section {{
            background: white;
            margin: 2rem auto;
            padding: 3rem;
            border-radius: 16px;
            box-shadow: var(--shadow-md);
        }}
        
        h2 {{
            font-family: 'Playfair Display', serif;
            font-size: 2rem;
            color: var(--primary-color);
            margin-bottom: 1.5rem;
            padding-bottom: 0.75rem;
            border-bottom: 3px solid var(--primary-color);
        }}
        
        /* About Section */
        .about-text {{
            font-size: 1.125rem;
            line-height: 1.8;
            color: var(--text-secondary);
            text-align: justify;
        }}
        
        /* Experience */
        .experience-item, .education-item, .project-item {{
            margin-bottom: 2rem;
            padding: 1.5rem;
            background: var(--bg-secondary);
            border-radius: 12px;
            border-left: 4px solid var(--primary-color);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }}
        
        .experience-item:hover, .education-item:hover, .project-item:hover {{
            transform: translateX(8px);
            box-shadow: var(--shadow-md);
        }}
        
        .item-title {{
            font-size: 1.5rem;
            font-weight: 600;
            color: var(--text-primary);
            margin-bottom: 0.25rem;
        }}
        
        .item-subtitle {{
            font-size: 1.125rem;
            color: var(--primary-color);
            font-weight: 500;
            margin-bottom: 0.5rem;
        }}
        
        .item-meta {{
            font-size: 0.875rem;
            color: var(--text-secondary);
            margin-bottom: 1rem;
        }}
        
        .item-description {{
            margin-top: 0.75rem;
            line-height: 1.6;
        }}
        
        ul {{
            margin-left: 1.5rem;
            margin-top: 0.5rem;
        }}
        
        li {{
            margin-bottom: 0.5rem;
            color: var(--text-secondary);
        }}
        
        /* Skills */
        .skills-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1.5rem;
            margin-top: 1.5rem;
        }}
        
        .skill-category {{
            background: var(--bg-secondary);
            padding: 1.5rem;
            border-radius: 12px;
            border-top: 3px solid var(--primary-color);
        }}
        
        .skill-category h3 {{
            font-size: 1rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: var(--primary-color);
            margin-bottom: 1rem;
        }}
        
        .skill-tags {{
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
        }}
        
        .skill-tag {{
            background: linear-gradient(135deg, var(--primary-color), var(--accent-color));
            color: white;
            padding: 0.4rem 0.8rem;
            border-radius: 6px;
            font-size: 0.875rem;
            font-weight: 500;
        }}
        
        /* Projects */
        .project-tech {{
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
            margin-top: 0.75rem;
        }}
        
        .tech-badge {{
            background: var(--bg-primary);
            border: 1px solid var(--border-color);
            padding: 0.25rem 0.75rem;
            border-radius: 4px;
            font-size: 0.8125rem;
            color: var(--text-secondary);
        }}
        
        /* Certifications */
        .cert-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 1rem;
            margin-top: 1rem;
        }}
        
        .cert-item {{
            background: var(--bg-secondary);
            padding: 1rem;
            border-radius: 8px;
            border-left: 3px solid var(--accent-color);
        }}
        
        .cert-name {{
            font-weight: 600;
            color: var(--text-primary);
            margin-bottom: 0.25rem;
        }}
        
        .cert-issuer {{
            font-size: 0.875rem;
            color: var(--text-secondary);
        }}
        
        /* Footer */
        footer {{
            text-align: center;
            padding: 3rem 0;
            color: var(--text-secondary);
            background: white;
            margin-top: 2rem;
            border-top: 1px solid var(--border-color);
        }}
        
        .footer-text {{
            font-size: 0.875rem;
        }}
        
        .powered-by {{
            margin-top: 0.5rem;
            font-size: 0.75rem;
            opacity: 0.7;
        }}
        
        /* Responsive */
        @media (max-width: 768px) {{
            h1 {{
                font-size: 2rem;
            }}
            
            .tagline {{
                font-size: 1rem;
            }}
            
            section {{
                padding: 2rem 1.5rem;
                margin: 1rem;
            }}
            
            .skills-grid {{
                grid-template-columns: 1fr;
            }}
            
            .contact-links {{
                flex-direction: column;
                align-items: center;
            }}
        }}
        
        /* Animations */
        @keyframes fadeIn {{
            from {{
                opacity: 0;
                transform: translateY(20px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}
        
        section {{
            animation: fadeIn 0.6s ease-out;
        }}
    </style>
</head>
<body>
    <!-- Header -->
    <header>
        <div class="container">
            <h1>{personal.get('name', 'Your Name')}</h1>
            <p class="tagline">{summary[:200] if summary else 'Professional Portfolio'}</p>
            
            <div class="contact-links">
                {f'<a href="mailto:{personal.get("email")}" class="contact-link">📧 Email</a>' if personal.get("email") else ''}
                {f'<a href="tel:{personal.get("phone")}" class="contact-link">📱 {personal.get("phone")}</a>' if personal.get("phone") else ''}
                {f'<a href="{personal.get("linkedin")}" target="_blank" class="contact-link">💼 LinkedIn</a>' if personal.get("linkedin") else ''}
                {f'<a href="{personal.get("github")}" target="_blank" class="contact-link">💻 GitHub</a>' if personal.get("github") else ''}
                {f'<a href="{personal.get("website")}" target="_blank" class="contact-link">🌐 Website</a>' if personal.get("website") else ''}
            </div>
        </div>
    </header>

    <div class="container">
        <!-- About Section -->
        {f'''<section id="about">
            <h2>About Me</h2>
            <p class="about-text">{summary}</p>
        </section>''' if summary else ''}

        <!-- Experience Section -->
        {f'''<section id="experience">
            <h2>Professional Experience</h2>
            {''.join([f"""
            <div class="experience-item">
                <div class="item-title">{exp.get('title', '')}</div>
                <div class="item-subtitle">{exp.get('company', '')}</div>
                <div class="item-meta">
                    {exp.get('start_date', '')} - {exp.get('end_date', 'Present')} 
                    {f'• {exp.get("location")}' if exp.get('location') else ''}
                </div>
                {f'<ul class="item-description">{"".join([f"<li>{resp}</li>" for resp in exp.get("responsibilities", [])])}</ul>' if exp.get('responsibilities') else ''}
            </div>
            """ for exp in experience])}
        </section>''' if experience else ''}

        <!-- Skills Section -->
        {f'''<section id="skills">
            <h2>Skills & Expertise</h2>
            <div class="skills-grid">
                {f"""<div class="skill-category">
                    <h3>Programming Languages</h3>
                    <div class="skill-tags">
                        {"".join([f'<span class="skill-tag">{skill}</span>' for skill in skills.get('programming_languages', [])])}
                    </div>
                </div>""" if skills.get('programming_languages') else ''}
                
                {f"""<div class="skill-category">
                    <h3>Frameworks & Libraries</h3>
                    <div class="skill-tags">
                        {"".join([f'<span class="skill-tag">{skill}</span>' for skill in skills.get('frameworks', [])])}
                    </div>
                </div>""" if skills.get('frameworks') else ''}
                
                {f"""<div class="skill-category">
                    <h3>Tools & Technologies</h3>
                    <div class="skill-tags">
                        {"".join([f'<span class="skill-tag">{skill}</span>' for skill in skills.get('tools', [])])}
                    </div>
                </div>""" if skills.get('tools') else ''}
                
                {f"""<div class="skill-category">
                    <h3>Databases</h3>
                    <div class="skill-tags">
                        {"".join([f'<span class="skill-tag">{skill}</span>' for skill in skills.get('databases', [])])}
                    </div>
                </div>""" if skills.get('databases') else ''}
                
                {f"""<div class="skill-category">
                    <h3>Cloud Platforms</h3>
                    <div class="skill-tags">
                        {"".join([f'<span class="skill-tag">{skill}</span>' for skill in skills.get('cloud', [])])}
                    </div>
                </div>""" if skills.get('cloud') else ''}
            </div>
        </section>''' if skills else ''}

        <!-- Projects Section -->
        {f'''<section id="projects">
            <h2>Projects</h2>
            {''.join([f"""
            <div class="project-item">
                <div class="item-title">{proj.get('name', '')}</div>
                {f"<p class='item-description'>{proj.get('description', '')}</p>" if proj.get('description') else ''}
                {f"<div class='project-tech'>{''.join([f'<span class=\"tech-badge\">{tech}</span>' for tech in proj.get('technologies', [])])}</div>" if proj.get('technologies') else ''}
                {f'<a href="{proj.get("url")}" target="_blank" style="color: var(--primary-color); margin-top: 0.5rem; display: inline-block;">View Project →</a>' if proj.get('url') else ''}
            </div>
            """ for proj in projects])}
        </section>''' if projects else ''}

        <!-- Education Section -->
        {f'''<section id="education">
            <h2>Education</h2>
            {''.join([f"""
            <div class="education-item">
                <div class="item-title">{edu.get('degree', '')}</div>
                <div class="item-subtitle">{edu.get('institution', '')}</div>
                <div class="item-meta">
                    {edu.get('graduation_year', '')}
                    {f'• {edu.get("location")}' if edu.get('location') else ''}
                </div>
            </div>
            """ for edu in education])}
        </section>''' if education else ''}

        <!-- Certifications Section -->
        {f'''<section id="certifications">
            <h2>Certifications</h2>
            <div class="cert-grid">
                {''.join([f"""
                <div class="cert-item">
                    <div class="cert-name">{cert.get('name', '')}</div>
                    <div class="cert-issuer">{cert.get('issuer', '')}</div>
                </div>
                """ for cert in certifications])}
            </div>
        </section>''' if certifications else ''}

        <!-- Awards Section -->
        {f'''<section id="awards">
            <h2>Awards & Achievements</h2>
            <ul>
                {''.join([f'<li><strong>{award.get("name", "")}</strong>{f" - {award.get("description", "")}" if award.get("description") else ""}</li>' for award in awards])}
            </ul>
        </section>''' if awards else ''}
    </div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <p class="footer-text">&copy; {datetime.now().year} {personal.get('name', 'Your Name')}. All rights reserved.</p>
            <p class="powered-by">Portfolio generated by <a href="https://viqri-cv.com" style="color: var(--primary-color); text-decoration: none;">Viqri CV</a></p>
        </div>
    </footer>
</body>
</html>'''
        
        return html
    
    def upload_file_to_repo(self, username: str, repo_name: str, 
                           file_path: str, content: str, 
                           commit_message: str = "Update portfolio") -> Dict:
        """
        Upload or update a file in GitHub repository
        
        Args:
            username: GitHub username
            repo_name: Repository name
            file_path: Path where file should be created (e.g., "index.html")
            content: File content
            commit_message: Git commit message
            
        Returns:
            dict with success status
        """
        try:
            # Check if file exists to get SHA
            file_url = f"{self.base_url}/repos/{username}/{repo_name}/contents/{file_path}"
            get_response = requests.get(file_url, headers=self.headers)
            
            sha = None
            if get_response.status_code == 200:
                sha = get_response.json().get("sha")
                logger.info(f"File {file_path} exists, will update")
            
            # Encode content to base64
            content_bytes = content.encode('utf-8')
            content_base64 = base64.b64encode(content_bytes).decode('utf-8')
            
            # Prepare data
            data = {
                "message": commit_message,
                "content": content_base64,
                "branch": "main"
            }
            
            if sha:
                data["sha"] = sha
            
            # Upload/update file
            response = requests.put(file_url, headers=self.headers, json=data)
            
            if response.status_code in [201, 200]:
                return {
                    "success": True,
                    "message": f"File {file_path} uploaded successfully"
                }
            else:
                error_msg = response.json().get('message', 'Unknown error')
                logger.error(f"Failed to upload file: {error_msg}")
                return {
                    "success": False,
                    "error": f"Failed to upload file: {error_msg}"
                }
                
        except Exception as e:
            logger.error(f"Error uploading file: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def deploy_portfolio(self, cv_data: Dict, username: str, 
                        repo_name: str = None) -> Dict:
        """
        Complete portfolio deployment workflow
        
        Args:
            cv_data: Extracted CV data
            username: GitHub username
            repo_name: Repository name (optional)
            
        Returns:
            dict with deployment status and URL
        """
        try:
            # Step 1: Create repository
            logger.info("Creating repository...")
            repo_result = self.create_repository(username, repo_name)
            
            if not repo_result.get("success"):
                return repo_result
            
            actual_repo_name = repo_result.get("repo_name")
            
            # Step 2: Generate HTML
            logger.info("Generating portfolio HTML...")
            html_content = self.generate_portfolio_html(cv_data)
            
            # Step 3: Upload to GitHub
            logger.info("Uploading to GitHub...")
            upload_result = self.upload_file_to_repo(
                username=username,
                repo_name=actual_repo_name,
                file_path="index.html",
                content=html_content,
                commit_message="Deploy portfolio from Viqri CV"
            )
            
            if not upload_result.get("success"):
                return upload_result
            
            # Calculate portfolio URL
            portfolio_url = f"https://{username}.github.io"
            if actual_repo_name != f"{username}.github.io":
                portfolio_url = f"https://{username}.github.io/{actual_repo_name}"
            
            return {
                "success": True,
                "message": "Portfolio deployed successfully!",
                "portfolio_url": portfolio_url,
                "repo_name": actual_repo_name,
                "note": "Your portfolio will be live in a few minutes at the URL above"
            }
            
        except Exception as e:
            logger.error(f"Error deploying portfolio: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }