name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    name: CI - Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/viqri-repo/viqri-cv:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/viqri-repo/viqri-cv:${{ github.sha }}

  deploy:
    name: Deploy to Cloud Run
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: production   # 🔒 Manual approval here

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy
        run: |
          gcloud run deploy viqri-cv-api \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/viqri-repo/viqri-cv:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars \
              GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
